// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyr_8krNjbW_dlxE7t_ygBGbBvM7iHLUM',
    appId: '1:485071886027:web:b2dadc6ef26f1f3bf8ad4e',
    messagingSenderId: '485071886027',
    projectId: 'hart-2349f',
    authDomain: 'hart-2349f.firebaseapp.com',
    storageBucket: 'hart-2349f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0gsfq34Wq-8al_UZjjIYgXfBipfnUieQ',
    appId: '1:485071886027:android:bb54500bdd1365f3f8ad4e',
    messagingSenderId: '485071886027',
    projectId: 'hart-2349f',
    storageBucket: 'hart-2349f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK6MfopTn5KaqrOiiA_2WcRwbEXjBOWJk',
    appId: '1:485071886027:ios:b23254f9fba4c0baf8ad4e',
    messagingSenderId: '485071886027',
    projectId: 'hart-2349f',
    storageBucket: 'hart-2349f.appspot.com',
    iosClientId: '485071886027-k3inhv8pdkl6nfl1ib45v9hp0ss8pus5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hummingArt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK6MfopTn5KaqrOiiA_2WcRwbEXjBOWJk',
    appId: '1:485071886027:ios:b23254f9fba4c0baf8ad4e',
    messagingSenderId: '485071886027',
    projectId: 'hart-2349f',
    storageBucket: 'hart-2349f.appspot.com',
    iosClientId: '485071886027-k3inhv8pdkl6nfl1ib45v9hp0ss8pus5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hummingArt',
  );
}
